# Generated by Django 5.1.6 on 2025-02-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='PENDING', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('conversation', 'message_id')},
        ),
    ]
