# Generated by Django 5.1.6 on 2025-02-18 10:34

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_message_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default=chat.models.generate_message_id, max_length=100, unique=True),
        ),
    ]
