# Generated by Django 5.1.6 on 2025-02-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=100, unique=True)),
                ('bot_token', models.CharField(max_length=255)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
